import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import "@/public/style/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="flex flex-col min-h-svh">
        <Header />
        <main className="flex-grow px-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
